default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username:
  password:
  host: localhost

development:
  <<: *default
  database: manyo3_dev

test:
  <<: *default
  database: manyo3_test

production:
  <<: *default
  database: manyo3
